version: '3'
services:
  scrape:
    ports:
     - "5001:5000"
    image: "allengeer/scraper"
  tone:
    links:
     - sidecar
    env_file:
     - env.lst
    image: "allengeer/toneanalysis"
  news:
    ports:
     - "5000:5000"
    image: "allengeer/tickernews"
  price:
    ports:
     - "5003:5000"
    image: "mlf4aiur/stock-price"
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - tone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5002:80"
  sidecar:
    image: redis
    volumes:
     - ".redis:/data"
    ports:
     - "6379:6379"