version: '2'
services:
  scrape:
    ports:
     - "5001:5000"
    image: "allengeer/scraper"
  tone:
    ports:
     - "5002:5000"
    env_file:
     - env.lst
    image: "allengeer/toneanalysis"
  news:
    ports:
     - "5000:5000"
    image: "allengeer/tickernews"
  price:
    ports:
     - "5003:5000"
    image: "mlf4aiur/stock-price"